spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:restaurant-voting;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
logging:
  level:
    root: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
springdoc:
  swagger-ui:
    path: /